# Generated by Django 4.0.6 on 2022-08-04 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_profile_bio_alter_profile_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='activation_pass',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
