# Generated by Django 4.0.6 on 2022-07-28 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_messagewithfriend'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessageWithFriend',
        ),
    ]
