# Generated by Django 4.1 on 2022-08-24 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_delete_messagewithfriend'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='last_message',
            field=models.JSONField(default=None),
            preserve_default=False,
        ),
    ]
