# Generated by Django 4.1 on 2022-08-24 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_room_last_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='last_message',
        ),
    ]
