# Generated by Django 4.1 on 2022-08-24 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0006_remove_room_last_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='last_message',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
