# Generated by Django 4.0.6 on 2022-08-01 09:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0002_friendrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagewithfriend',
            old_name='reciever',
            new_name='receiver',
        ),
        migrations.AddField(
            model_name='messagewithfriend',
            name='message',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
