# Generated by Django 4.2.1 on 2023-06-01 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0004_rename_reciever_friendrequest_receiver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagewithfriend',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='images/messagewithfriend'),
        ),
    ]
